.SUFFIXES: .o .c

CC = gcc
CFLAGS = -g -O3
LFLAGS = -lm -pthread

CTAGS = ctags
BIN = p_gauss
CFILES = gauss_pthread.c
OBJECTS = gauss_pthread.o
HFILES =
OTHERSOURCES =
SOURCES =   $(HFILES) $(CFILES) $(OTHERSOURCES)

.c.o:
	$(CC) -c $(CFLAGS) $*.c

$(BIN): $(OBJECTS)
	$(CC) $(LFLAGS) -o $(BIN) $(OBJECTS)

tags: $(CFILES) $(HFILES) $(EXTRACTCFILES) $(RECOGCFILES)
# for vi:
	$(CTAGS) -d -t -T -w $(CFILES) $(HFILES)
	sort -o tags tags

clean:
	-rm $(BIN) $(OBJECTS)
