.SUFFIXES: .o .c

CC = mpicc
CFLAGS = -g -O3
LFLAGS =

CTAGS = ctags
BIN = mpi_gauss
CFILES = gauss_mpi.c
OBJECTS = gauss_mpi.o
HFILES =
OTHERSOURCES =
SOURCES =   $(HFILES) $(CFILES) $(OTHERSOURCES)

.c.o:
	$(CC) -c $(CFLAGS) $*.c

$(BIN): $(OBJECTS)
	$(CC) $(LFLAGS) -o $(BIN) $(OBJECTS)

tags: $(CFILES) $(HFILES) $(EXTRACTCFILES) $(RECOGCFILES)
# for vi:
	$(CTAGS) -d -t -T -w $(CFILES) $(HFILES)
	sort -o tags tags

clean:
	-rm $(BIN) $(OBJECTS)
