.SUFFIXES: .o .c

CC = gcc
CFLAGS = -g -fopenmp
LFLAGS =

CTAGS = ctags
BIN = omp_gauss
CFILES = gauss_omp.c
OBJECTS = gauss_omp.o
HFILES =
OTHERSOURCES =
SOURCES =   $(HFILES) $(CFILES) $(OTHERSOURCES)

.c.o:
	$(CC) -c $(CFLAGS) $*.c

$(BIN): $(OBJECTS)
	$(CC) $(LFLAGS) -o $(BIN) $(OBJECTS)

tags: $(CFILES) $(HFILES) $(EXTRACTCFILES) $(RECOGCFILES)
# for vi:
	$(CTAGS) -d -t -T -w $(CFILES) $(HFILES)
	sort -o tags tags

clean:
	-rm $(BIN) $(OBJECTS)