#!/bin/bash

size=128
filename="test_${size}.txt"

module load mpi

make -f Makefile.omp
make -f Makefile.mpi
make -f Makefile.pthread

touch $filename

# -------------------1 proc --------------------
echo "1 processor test."
echo "1 process" >> $filename

./p_gauss -s $size -n 1 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 1 >> $filename
echo "omp completed."

mpirun -np 1 ./mpi_gauss -s $size >> $filename
echo "mpi completed."


# ------------------2 proc---------------------
echo "2 processor test."
echo -e "\n2 process" >> $filename

./p_gauss -s $size -n 2 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 2 >> $filename
echo "omp completed."

mpirun -np 2 ./mpi_gauss -s $size >> $filename
echo "mpi completed."


# ------------------4 proc --------------------
echo "4 processor test."
echo -e "\n4 process" >> $filename

./p_gauss -s $size -n 4 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 4 >> $filename
echo "omp completed."

mpirun -np 4 ./mpi_gauss -s $size >> $filename
echo "mpi completed."

# ------------------8 proc --------------------
echo "8 processor test."
echo -e "\n8 process" >> $filename

./p_gauss -s $size -n 8 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 8 >> $filename
echo "omp completed."

mpirun -np 8 ./mpi_gauss -s $size >> $filename
echo "mpi completed."

# ------------------16 proc --------------------
echo "16 processor test."
echo -e "\n16 process" >> $filename

./p_gauss -s $size -n 16 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 16 >> $filename
echo "omp completed."

mpirun -np 16 ./mpi_gauss -s $size >> $filename
echo "mpi completed."

# ------------------32 proc --------------------
echo "32 processor test."
echo -e "\n32 process" >> $filename

./p_gauss -s $size -n 32 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 32 >> $filename
echo "omp completed."

mpirun -np 32 ./mpi_gauss -s $size >> $filename
echo "mpi completed."

# ------------------64 proc --------------------
echo "64 processor test."
echo -e "\n64 process" >> $filename

./p_gauss -s $size -n 64 >> $filename
echo "pthread completed."

./omp_gauss -s $size -n 64 >> $filename
echo "omp completed."

mpirun -np 64 ./mpi_gauss -s $size >> $filename
echo "mpi completed."


rm mpi_gauss omp_gauss p_gauss
